POST https://canary.discord.com/api/v9/interactions
Authorization: {{token}}
Content-Type: application/json

{
   "type":3,
   "guild_id":"750031320205230311",
   "channel_id":"750031320205230314",
   "message_flags":0,
   "message_id":"865828647590690816",
   "application_id":"735835853372522546",
   "data":{
      "component_type":3,
      "custom_id":"select",
      "hash":"ndp3LH8f",
      "values":[
         "1",
         "2",
         "100"
      ]
   }
}